-- Editable Downtown table maps shared by /test/table.html and /test/queen.html.
-- Run once in the Supabase SQL editor.

begin;

create table if not exists public.dining_table_layouts (
  id bigint generated by default as identity primary key,
  branch text not null,
  zone text not null,
  canvas_width integer not null default 1200,
  canvas_height integer not null default 800,
  items jsonb not null default '[]'::jsonb,
  revision integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dining_table_layouts_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_table_layouts_zone_check
    check (zone in ('overview', 'first', 'second', 'patio')),
  constraint dining_table_layouts_canvas_width_check
    check (canvas_width between 600 and 2400),
  constraint dining_table_layouts_canvas_height_check
    check (canvas_height between 400 and 1800),
  constraint dining_table_layouts_items_array_check
    check (jsonb_typeof(items) = 'array'),
  constraint dining_table_layouts_branch_zone_unique
    unique (branch, zone)
);

-- Keep existing installations in sync when this setup script is rerun.
alter table public.dining_table_layouts
  drop constraint if exists dining_table_layouts_zone_check;
alter table public.dining_table_layouts
  add constraint dining_table_layouts_zone_check
  check (zone in ('overview', 'first', 'second', 'patio'));

create or replace function public.set_dining_table_layout_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  new.revision = old.revision + 1;
  return new;
end;
$$;

drop trigger if exists dining_table_layouts_set_updated_at
on public.dining_table_layouts;
create trigger dining_table_layouts_set_updated_at
before update on public.dining_table_layouts
for each row
execute function public.set_dining_table_layout_updated_at();

create or replace function public.save_dining_table_layout(
  p_branch text,
  p_zone text,
  p_canvas_width integer,
  p_canvas_height integer,
  p_items jsonb
)
returns public.dining_table_layouts
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_zone text := lower(trim(p_zone));
  saved_layout public.dining_table_layouts;
begin
  if normalized_branch is null
    or normalized_branch !~ '^[a-z0-9_-]{1,40}$'
  then
    raise exception 'Invalid branch';
  end if;

  if normalized_zone is null
    or normalized_zone not in ('overview', 'first', 'second', 'patio')
  then
    raise exception 'Invalid map zone';
  end if;

  if p_canvas_width is null or p_canvas_width not between 600 and 2400
    or p_canvas_height is null or p_canvas_height not between 400 and 1800
  then
    raise exception 'Invalid canvas dimensions';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Map items must be a JSON array';
  end if;

  if jsonb_array_length(p_items) > 250
    or octet_length(p_items::text) > 250000
  then
    raise exception 'Map payload is too large';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_items) as element(item)
    where jsonb_typeof(element.item) <> 'object'
      or coalesce(element.item->>'type', '') not in ('table', 'obstacle')
      or length(coalesce(element.item->>'id', '')) not between 1 and 80
      or length(coalesce(element.item->>'label', '')) > 80
      or length(coalesce(element.item->>'tableCode', '')) > 40
  ) then
    raise exception 'One or more map items are invalid';
  end if;

  if normalized_zone = 'overview' and (
    jsonb_array_length(p_items) <> 3
    or exists (
      select 1
      from jsonb_array_elements(p_items) as element(item)
      where coalesce(element.item->>'type', '') <> 'obstacle'
        or coalesce(element.item->>'targetZone', '') not in ('first', 'second', 'patio')
    )
    or (
      select count(distinct element.item->>'targetZone')
      from jsonb_array_elements(p_items) as element(item)
    ) <> 3
  ) then
    raise exception 'Overview must contain one frame for each map zone';
  end if;

  insert into public.dining_table_layouts (
    branch,
    zone,
    canvas_width,
    canvas_height,
    items
  )
  values (
    normalized_branch,
    normalized_zone,
    p_canvas_width,
    p_canvas_height,
    p_items
  )
  on conflict (branch, zone)
  do update set
    canvas_width = excluded.canvas_width,
    canvas_height = excluded.canvas_height,
    items = excluded.items
  returning * into saved_layout;

  return saved_layout;
end;
$$;

alter table public.dining_table_layouts enable row level security;

revoke all on table public.dining_table_layouts from anon, authenticated;
grant select on table public.dining_table_layouts to anon, authenticated;

revoke all on function public.save_dining_table_layout(
  text,
  text,
  integer,
  integer,
  jsonb
) from public;
grant execute on function public.save_dining_table_layout(
  text,
  text,
  integer,
  integer,
  jsonb
) to anon, authenticated;

drop policy if exists dining_table_layouts_public_select
on public.dining_table_layouts;
create policy dining_table_layouts_public_select
on public.dining_table_layouts
for select
to anon, authenticated
using (true);

insert into public.dining_table_layouts (
  branch,
  zone,
  canvas_width,
  canvas_height,
  items
)
values (
  'downtown',
  'overview',
  1600,
  900,
  '[
    {"id":"overview-first","type":"obstacle","tableCode":"","label":"1st Floor","obstacleKind":"service","shape":"rectangle","targetZone":"first","x":2.2,"y":3.5,"w":59.5,"h":93,"rotation":0},
    {"id":"overview-second","type":"obstacle","tableCode":"","label":"2nd Floor","obstacleKind":"service","shape":"rectangle","targetZone":"second","x":70.2,"y":3.5,"w":27.6,"h":42,"rotation":0},
    {"id":"overview-patio","type":"obstacle","tableCode":"","label":"Patio","obstacleKind":"service","shape":"rectangle","targetZone":"patio","x":70.2,"y":54.5,"w":27.6,"h":42,"rotation":0}
  ]'::jsonb
)
on conflict (branch, zone) do nothing;

comment on table public.dining_table_layouts is
  'Saved floor maps for table placement and fixed reference obstacles.';
comment on column public.dining_table_layouts.items is
  'JSON array of table and obstacle items using percentage-based coordinates.';

commit;
