-- EHWA Party-first table seating with a reusable QR pool.
-- Run after dining-party-guest-architecture.sql.
--
-- Tables are selected first. One or more QR codes are then assigned to the
-- selected Party. QR codes are released when the Party closes, while every
-- historical order keeps its original Table and QR session.

begin;

create table if not exists public.dining_party_qrs (
  id bigint generated by default as identity primary key,
  branch text not null,
  party_id bigint not null references public.dining_parties (id) on delete restrict,
  table_id bigint not null references public.dining_tables (id) on delete restrict,
  qr_number integer not null,
  assigned_at timestamptz not null default now(),
  released_at timestamptz,
  constraint dining_party_qrs_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_party_qrs_number_check
    check (qr_number between 1 and 10),
  constraint dining_party_qrs_release_check
    check (released_at is null or released_at >= assigned_at)
);

create unique index if not exists dining_party_qrs_one_active_qr
  on public.dining_party_qrs (branch, qr_number)
  where released_at is null;

create index if not exists dining_party_qrs_party_history_idx
  on public.dining_party_qrs (party_id, assigned_at desc);

create index if not exists dining_party_qrs_table_history_idx
  on public.dining_party_qrs (table_id, assigned_at desc);

-- Multiple QR codes may intentionally point to one physical table.
drop index if exists public.dining_qr_sessions_one_active_table;

-- Preserve active assignments created by the previous architecture.
insert into public.dining_party_qrs (
  branch,
  party_id,
  table_id,
  qr_number
)
select
  table_record.branch,
  table_record.current_party_id,
  table_record.id,
  table_record.qr_number
from public.dining_tables as table_record
join public.dining_parties as party
  on party.id = table_record.current_party_id
 and party.status = 'ACTIVE'
where table_record.qr_number is not null
  and not exists (
    select 1
    from public.dining_party_qrs as party_qr
    where party_qr.branch = table_record.branch
      and party_qr.qr_number = table_record.qr_number
      and party_qr.released_at is null
  );

-- dining_tables.qr_number remains a compatibility-only primary QR. Empty
-- tables must no longer keep a QR reserved.
update public.dining_tables
set qr_number = null
where current_party_id is null
  and qr_number is not null;

create or replace function public.sync_dining_table_primary_qr(
  p_table_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.dining_tables as table_record
  set qr_number = (
    select min(party_qr.qr_number)
    from public.dining_party_qrs as party_qr
    where party_qr.table_id = p_table_id
      and party_qr.released_at is null
  )
  where table_record.id = p_table_id;
end;
$$;

create or replace function public.sync_dining_party_qr_table()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    perform public.sync_dining_table_primary_qr(old.table_id);
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    if tg_op <> 'UPDATE' or new.table_id is distinct from old.table_id then
      perform public.sync_dining_table_primary_qr(new.table_id);
    elsif new.released_at is distinct from old.released_at
      or new.qr_number is distinct from old.qr_number
    then
      perform public.sync_dining_table_primary_qr(new.table_id);
    end if;
  end if;

  return null;
end;
$$;

drop trigger if exists dining_party_qrs_sync_table on public.dining_party_qrs;
create trigger dining_party_qrs_sync_table
after insert or update or delete on public.dining_party_qrs
for each row
execute function public.sync_dining_party_qr_table();

create or replace function public.release_dining_party_qrs()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status = 'ACTIVE' and new.status <> 'ACTIVE' then
    update public.dining_qr_sessions as session
    set status = 'closed',
        ended_at = coalesce(session.ended_at, now()),
        ended_reason = coalesce(nullif(new.closed_reason, ''), 'party-closed')
    where session.branch = new.branch
      and session.status = 'active'
      and exists (
        select 1
        from public.dining_party_qrs as party_qr
        where party_qr.party_id = new.id
          and party_qr.qr_number = session.qr_number
          and party_qr.released_at is null
      );

    update public.dining_party_qrs
    set released_at = now()
    where party_id = new.id
      and released_at is null;
  end if;

  return new;
end;
$$;

drop trigger if exists dining_parties_release_qrs on public.dining_parties;
create trigger dining_parties_release_qrs
after update of status on public.dining_parties
for each row
execute function public.release_dining_party_qrs();

create or replace function public.configure_dining_party_qrs(
  p_branch text,
  p_table_codes text[],
  p_qr_numbers integer[],
  p_party_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_codes text[] := array[]::text[];
  normalized_qrs integer[] := array[]::integer[];
  selected_code text;
  selected_qr integer;
  code_count integer;
  qr_count integer;
  table_ids bigint[] := array[]::bigint[];
  table_codes text[] := array[]::text[];
  table_record public.dining_tables;
  target_party public.dining_parties;
  table_index integer;
  qr_index integer;
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;

  for selected_code in
    select trim(input.code)
    from unnest(coalesce(p_table_codes, array[]::text[]))
      with ordinality as input(code, position)
    where nullif(trim(input.code), '') is not null
    order by input.position
  loop
    if char_length(selected_code) > 40 then
      raise exception 'Invalid table code';
    end if;
    if not exists (
      select 1
      from unnest(normalized_codes) as existing(code)
      where lower(existing.code) = lower(selected_code)
    ) then
      normalized_codes := array_append(normalized_codes, selected_code);
    end if;
  end loop;

  for selected_qr in
    select input.qr_number
    from unnest(coalesce(p_qr_numbers, array[]::integer[]))
      with ordinality as input(qr_number, position)
    where input.qr_number is not null
    order by input.position
  loop
    if selected_qr not between 1 and 10 then
      raise exception 'QR number must be between 1 and 10';
    end if;
    if array_position(normalized_qrs, selected_qr) is null then
      normalized_qrs := array_append(normalized_qrs, selected_qr);
    end if;
  end loop;

  code_count := coalesce(array_length(normalized_codes, 1), 0);
  qr_count := coalesce(array_length(normalized_qrs, 1), 0);
  if code_count < 1 or code_count > 30 then
    raise exception 'Select between 1 and 30 tables';
  end if;
  if qr_count < 1 or qr_count > 10 then
    raise exception 'Select between 1 and 10 QR codes';
  end if;

  perform pg_advisory_xact_lock(hashtext('party-qr:' || normalized_branch));

  if p_party_id is not null then
    select party.*
    into target_party
    from public.dining_parties as party
    where party.id = p_party_id
      and party.branch = normalized_branch
      and party.status = 'ACTIVE'
    for update;

    if not found then
      raise exception 'Active Party not found';
    end if;
  end if;

  for table_index in 1..code_count loop
    select candidate.*
    into table_record
    from public.dining_tables as candidate
    where candidate.branch = normalized_branch
      and lower(candidate.table_code) = lower(normalized_codes[table_index])
    for update;

    if table_record.id is null then
      insert into public.dining_tables (branch, table_code)
      values (normalized_branch, normalized_codes[table_index])
      returning * into table_record;
    elsif table_record.current_party_id is not null then
      raise exception 'Table % already belongs to an active Party', table_record.table_code;
    end if;

    table_ids := array_append(table_ids, table_record.id);
    table_codes := array_append(table_codes, table_record.table_code);
  end loop;

  if exists (
    select 1
    from public.dining_party_qrs as party_qr
    where party_qr.branch = normalized_branch
      and party_qr.qr_number = any(normalized_qrs)
      and party_qr.released_at is null
  ) then
    raise exception 'One or more selected QR codes are already active';
  end if;

  if p_party_id is null then
    insert into public.dining_parties (branch)
    values (normalized_branch)
    returning * into target_party;
  end if;

  update public.dining_tables
  set current_party_id = target_party.id
  where id = any(table_ids);

  insert into public.dining_party_tables (party_id, table_id)
  select target_party.id, selected_table_id
  from unnest(table_ids) as selected(selected_table_id);

  -- Clear any dangling compatibility sessions before creating the new active
  -- sessions. The Party QR table above remains the source of truth.
  update public.dining_qr_sessions
  set status = 'closed',
      ended_at = coalesce(ended_at, now()),
      ended_reason = 'party-qr-reassigned'
  where branch = normalized_branch
    and status = 'active'
    and qr_number = any(normalized_qrs);

  for qr_index in 1..qr_count loop
    table_index := ((qr_index - 1) % code_count) + 1;

    insert into public.dining_party_qrs (
      branch,
      party_id,
      table_id,
      qr_number
    )
    values (
      normalized_branch,
      target_party.id,
      table_ids[table_index],
      normalized_qrs[qr_index]
    );

    insert into public.dining_qr_sessions (
      branch,
      qr_number,
      table_code
    )
    values (
      normalized_branch,
      normalized_qrs[qr_index],
      table_codes[table_index]
    );
  end loop;

  return jsonb_build_object(
    'party_id', target_party.id,
    'status', target_party.status,
    'table_codes', table_codes,
    'qr_numbers', normalized_qrs
  );
end;
$$;

create or replace function public.resolve_dining_guest(
  p_branch text,
  p_qr_number integer,
  p_guest_id uuid default null,
  p_device_info jsonb default '{}'::jsonb,
  p_current_page text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  active_table public.dining_tables;
  active_party public.dining_parties;
  resolved_guest public.dining_guests;
  compatibility_session_id bigint;
  safe_device_info jsonb := coalesce(p_device_info, '{}'::jsonb);
  safe_page text := left(coalesce(p_current_page, ''), 300);
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'Invalid QR number';
  end if;
  if jsonb_typeof(safe_device_info) <> 'object'
    or octet_length(safe_device_info::text) > 12000
  then
    safe_device_info := '{}'::jsonb;
  end if;

  update public.dining_guests
  set status = 'EXPIRED'
  where status = 'ACTIVE'
    and expires_at <= now();

  select table_record.*
  into active_table
  from public.dining_party_qrs as party_qr
  join public.dining_tables as table_record
    on table_record.id = party_qr.table_id
   and table_record.current_party_id = party_qr.party_id
  join public.dining_parties as party
    on party.id = party_qr.party_id
   and party.status = 'ACTIVE'
  where party_qr.branch = normalized_branch
    and party_qr.qr_number = p_qr_number
    and party_qr.released_at is null
  limit 1;

  if not found then
    raise exception 'This QR is not assigned to an active Party';
  end if;

  select party.*
  into active_party
  from public.dining_parties as party
  where party.id = active_table.current_party_id
    and party.status = 'ACTIVE';

  if p_guest_id is not null then
    select guest.*
    into resolved_guest
    from public.dining_guests as guest
    where guest.id = p_guest_id
      and guest.branch = normalized_branch
      and guest.party_id = active_party.id
      and guest.status = 'ACTIVE'
      and guest.expires_at > now()
    for update;
  end if;

  if resolved_guest.id is null then
    insert into public.dining_guests (
      branch,
      display_code,
      party_id,
      current_table_id,
      device_info,
      current_page
    )
    values (
      normalized_branch,
      public.create_dining_guest_display_code(normalized_branch),
      active_party.id,
      active_table.id,
      safe_device_info,
      safe_page
    )
    returning * into resolved_guest;

    insert into public.dining_guest_events (guest_id, event_type, detail)
    values (
      resolved_guest.id,
      'CREATED',
      jsonb_build_object(
        'party_id', active_party.id,
        'table_id', active_table.id,
        'table_code', active_table.table_code
      )
    );
  else
    if resolved_guest.current_page is distinct from safe_page then
      insert into public.dining_guest_events (guest_id, event_type, detail)
      values (
        resolved_guest.id,
        'PAGE_CHANGED',
        jsonb_build_object(
          'from', resolved_guest.current_page,
          'to', safe_page,
          'table_code', active_table.table_code
        )
      );
    end if;

    update public.dining_guests
    set last_seen_at = now(),
        current_table_id = active_table.id,
        current_page = safe_page,
        device_info = case
          when safe_device_info = '{}'::jsonb then device_info
          else safe_device_info
        end
    where id = resolved_guest.id
    returning * into resolved_guest;
  end if;

  select session.id
  into compatibility_session_id
  from public.dining_qr_sessions as session
  where session.branch = normalized_branch
    and session.qr_number = p_qr_number
    and session.status = 'active'
  order by session.started_at desc
  limit 1;

  return jsonb_build_object(
    'guest_id', resolved_guest.id,
    'display_code', resolved_guest.display_code,
    'guest_status', resolved_guest.status,
    'created_at', resolved_guest.created_at,
    'expires_at', resolved_guest.expires_at,
    'party_id', active_party.id,
    'party_status', active_party.status,
    'table_id', active_table.id,
    'table_code', active_table.table_code,
    'qr_number', p_qr_number,
    'qr_session_id', compatibility_session_id
  );
end;
$$;

create or replace function public.validate_dining_request_qr_session()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  active_session public.dining_qr_sessions;
  active_guest public.dining_guests;
  active_table public.dining_tables;
begin
  if new.guest_id is not null then
    select guest.*
    into active_guest
    from public.dining_guests as guest
    where guest.id = new.guest_id
      and guest.branch = new.branch
      and guest.status = 'ACTIVE'
      and guest.expires_at > now();

    if not found then
      raise exception 'An active Guest is required';
    end if;

    select table_record.*
    into active_table
    from public.dining_tables as table_record
    join public.dining_parties as party
      on party.id = table_record.current_party_id
     and party.status = 'ACTIVE'
    where table_record.id = new.table_id
      and table_record.branch = new.branch
      and table_record.current_party_id = active_guest.party_id;

    if not found then
      raise exception 'The Table does not belong to the Guest Party';
    end if;

    if new.qr_number is null or not exists (
      select 1
      from public.dining_party_qrs as party_qr
      where party_qr.branch = new.branch
        and party_qr.party_id = active_guest.party_id
        and party_qr.table_id = active_table.id
        and party_qr.qr_number = new.qr_number
        and party_qr.released_at is null
    ) then
      raise exception 'The QR does not belong to this Party Table';
    end if;

    new.party_id = active_guest.party_id;
    new.table_id = active_table.id;
    new.table_code = active_table.table_code;
    return new;
  end if;

  if new.qr_session_id is null or new.qr_number is null then
    raise exception 'An active QR session or Guest is required';
  end if;

  select session.*
  into active_session
  from public.dining_qr_sessions as session
  where session.id = new.qr_session_id
    and session.branch = new.branch
    and session.qr_number = new.qr_number
    and session.status = 'active'
    and nullif(trim(session.table_code), '') is not null;

  if not found then
    raise exception 'The QR is not assigned to an active table';
  end if;

  new.table_code = active_session.table_code;
  return new;
end;
$$;

create or replace function public.submit_dining_request_v2(
  p_branch text,
  p_qr_number integer,
  p_guest_id uuid,
  p_kind text,
  p_request_type text,
  p_note text default '',
  p_items jsonb default '[]'::jsonb
)
returns public.dining_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_kind text := lower(trim(p_kind));
  normalized_request_type text := lower(trim(p_request_type));
  active_guest public.dining_guests;
  active_table public.dining_tables;
  new_request public.dining_requests;
  compatibility_session_id bigint;
  calculated_item_count integer := 0;
  calculated_subtotal numeric(10, 2) := 0;
  calculated_tax numeric(10, 2) := 0;
  calculated_total numeric(10, 2) := 0;
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if p_guest_id is null then
    raise exception 'Guest is required';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'Invalid QR number';
  end if;
  if normalized_kind is null or normalized_kind not in ('order', 'service') then
    raise exception 'Invalid request kind';
  end if;
  if normalized_request_type is null or normalized_request_type not in ('order', 'water', 'napkins', 'server') then
    raise exception 'Invalid request type';
  end if;
  if p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) > 60
    or octet_length(p_items::text) > 120000
  then
    raise exception 'Invalid order items';
  end if;

  select guest.*
  into active_guest
  from public.dining_guests as guest
  join public.dining_parties as party
    on party.id = guest.party_id
   and party.status = 'ACTIVE'
  where guest.id = p_guest_id
    and guest.branch = normalized_branch
    and guest.status = 'ACTIVE'
    and guest.expires_at > now()
  for update;

  if not found then
    raise exception 'Guest is no longer active';
  end if;

  select table_record.*
  into active_table
  from public.dining_party_qrs as party_qr
  join public.dining_tables as table_record
    on table_record.id = party_qr.table_id
   and table_record.current_party_id = party_qr.party_id
  where party_qr.branch = normalized_branch
    and party_qr.party_id = active_guest.party_id
    and party_qr.qr_number = p_qr_number
    and party_qr.released_at is null;

  if not found then
    raise exception 'This QR does not belong to the Guest Party';
  end if;

  if normalized_kind = 'order' then
    if normalized_request_type <> 'order' or jsonb_array_length(p_items) < 1 then
      raise exception 'An order requires one or more menu items';
    end if;

    if exists (
      select 1
      from jsonb_array_elements(p_items) as element(item)
      where nullif(trim(element.item->>'menuId'), '') is null
        or coalesce(element.item->>'quantity', '') !~ '^[0-9]+$'
        or (element.item->>'quantity')::integer not between 1 and 50
        or coalesce(element.item->>'unitPrice', '') !~ '^[0-9]+([.][0-9]{1,2})?$'
        or (element.item->>'unitPrice')::numeric < 0
        or (element.item->>'unitPrice')::numeric > 9999.99
    ) then
      raise exception 'One or more menu items are invalid';
    end if;

    select
      coalesce(sum((element.item->>'quantity')::integer), 0),
      coalesce(sum(
        (element.item->>'quantity')::integer
        * (element.item->>'unitPrice')::numeric
      ), 0)
    into calculated_item_count, calculated_subtotal
    from jsonb_array_elements(p_items) as element(item);

    calculated_subtotal := round(calculated_subtotal, 2);
    calculated_tax := round(calculated_subtotal * 0.13, 2);
    calculated_total := calculated_subtotal + calculated_tax;
    if calculated_item_count > 100 then
      raise exception 'An order cannot contain more than 100 items';
    end if;
  else
    if normalized_request_type = 'order' or jsonb_array_length(p_items) <> 0 then
      raise exception 'A service request cannot contain menu items';
    end if;
  end if;

  select session.id
  into compatibility_session_id
  from public.dining_qr_sessions as session
  where session.branch = normalized_branch
    and session.qr_number = p_qr_number
    and session.status = 'active'
  order by session.started_at desc
  limit 1;

  insert into public.dining_requests (
    branch,
    table_code,
    guest_count,
    kind,
    request_type,
    status,
    source,
    qr_number,
    qr_session_id,
    party_id,
    guest_id,
    table_id,
    added_by,
    note,
    items,
    item_count,
    subtotal,
    tax,
    total
  )
  values (
    normalized_branch,
    active_table.table_code,
    1,
    normalized_kind,
    normalized_request_type,
    'new',
    case when normalized_kind = 'order' then 'table-qr' else 'table-service-call' end,
    p_qr_number,
    compatibility_session_id,
    active_guest.party_id,
    active_guest.id,
    active_table.id,
    'guest',
    left(coalesce(p_note, ''), 1000),
    p_items,
    calculated_item_count,
    calculated_subtotal,
    calculated_tax,
    calculated_total
  )
  returning * into new_request;

  if normalized_kind = 'order' then
    insert into public.dining_order_items (
      request_id,
      guest_id,
      party_id,
      table_id,
      menu_id,
      name_ko,
      name_en,
      quantity,
      unit_price,
      line_total,
      note
    )
    select
      new_request.id,
      active_guest.id,
      active_guest.party_id,
      active_table.id,
      left(trim(element.item->>'menuId'), 120),
      left(coalesce(element.item->>'nameKo', ''), 200),
      left(coalesce(element.item->>'nameEn', ''), 200),
      (element.item->>'quantity')::integer,
      round((element.item->>'unitPrice')::numeric, 2),
      round(
        (element.item->>'quantity')::integer
        * (element.item->>'unitPrice')::numeric,
        2
      ),
      left(coalesce(element.item->>'note', ''), 500)
    from jsonb_array_elements(p_items) as element(item);
  end if;

  insert into public.dining_order_events (
    request_id,
    event_type,
    next_value,
    actor
  )
  values (
    new_request.id,
    'CREATED',
    jsonb_build_object(
      'status', new_request.status,
      'table_id', active_table.id,
      'table_code', active_table.table_code,
      'guest_id', active_guest.id,
      'qr_number', p_qr_number
    ),
    'guest'
  );

  update public.dining_guests
  set last_seen_at = now(),
      current_table_id = active_table.id,
      current_page = '/test/menu/'
  where id = active_guest.id;

  return new_request;
end;
$$;

create or replace function public.get_active_dining_party_qrs(
  p_branch text
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(to_jsonb(active_qr) order by active_qr.qr_number),
    '[]'::jsonb
  )
  from (
    select
      party_qr.id,
      party_qr.branch,
      party_qr.party_id,
      party_qr.table_id,
      table_record.table_code,
      party_qr.qr_number,
      party_qr.assigned_at
    from public.dining_party_qrs as party_qr
    join public.dining_tables as table_record
      on table_record.id = party_qr.table_id
    join public.dining_parties as party
      on party.id = party_qr.party_id
     and party.status = 'ACTIVE'
    where party_qr.branch = lower(trim(p_branch))
      and party_qr.released_at is null
  ) as active_qr;
$$;

alter table public.dining_party_qrs enable row level security;
revoke all on table public.dining_party_qrs from anon, authenticated;

revoke all on function public.sync_dining_table_primary_qr(bigint) from public;
revoke all on function public.configure_dining_party_qrs(text, text[], integer[], bigint) from public;
revoke all on function public.resolve_dining_guest(text, integer, uuid, jsonb, text) from public;
revoke all on function public.submit_dining_request_v2(text, integer, uuid, text, text, text, jsonb) from public;
revoke all on function public.get_active_dining_party_qrs(text) from public;

grant execute on function public.configure_dining_party_qrs(text, text[], integer[], bigint)
  to anon, authenticated;
grant execute on function public.resolve_dining_guest(text, integer, uuid, jsonb, text)
  to anon, authenticated;
grant execute on function public.submit_dining_request_v2(text, integer, uuid, text, text, text, jsonb)
  to anon, authenticated;
grant execute on function public.get_active_dining_party_qrs(text)
  to anon, authenticated;

comment on table public.dining_party_qrs is
  'Reusable QR assignments active only for the lifetime of one Party; orders retain origin Table history.';

comment on column public.dining_tables.qr_number is
  'Compatibility-only primary active QR. dining_party_qrs is the source of truth.';

commit;
