-- Shared queue for table orders and service calls created by the guest menu.
-- Run this once in the Supabase SQL editor before testing /test/menu/.

begin;

create table if not exists public.dining_requests (
  id bigint generated by default as identity primary key,
  branch text not null,
  table_code text not null,
  guest_count integer not null default 0,
  kind text not null,
  request_type text not null,
  status text not null default 'new',
  source text not null default 'table-qr',
  note text not null default '',
  items jsonb not null default '[]'::jsonb,
  item_count integer not null default 0,
  subtotal numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dining_requests_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_requests_table_code_check
    check (char_length(trim(table_code)) between 1 and 40),
  constraint dining_requests_guest_count_check
    check (guest_count between 0 and 100),
  constraint dining_requests_kind_check
    check (kind in ('order', 'service')),
  constraint dining_requests_type_check
    check (request_type in ('order', 'water', 'napkins', 'server')),
  constraint dining_requests_status_check
    check (status in ('new', 'acknowledged', 'preparing', 'ready', 'completed', 'canceled')),
  constraint dining_requests_items_check
    check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) <= 60),
  constraint dining_requests_item_count_check
    check (item_count between 0 and 100),
  constraint dining_requests_totals_check
    check (subtotal >= 0 and tax >= 0 and total >= 0),
  constraint dining_requests_shape_check
    check (
      (
        kind = 'order'
        and request_type = 'order'
        and item_count > 0
        and jsonb_array_length(items) > 0
      )
      or
      (
        kind = 'service'
        and request_type <> 'order'
        and item_count = 0
        and jsonb_array_length(items) = 0
        and subtotal = 0
        and tax = 0
        and total = 0
      )
    )
);

create index if not exists dining_requests_branch_status_created_idx
  on public.dining_requests (branch, status, created_at desc);

create or replace function public.set_dining_request_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists dining_requests_set_updated_at on public.dining_requests;
create trigger dining_requests_set_updated_at
before update on public.dining_requests
for each row
execute function public.set_dining_request_updated_at();

alter table public.dining_requests enable row level security;

revoke all on table public.dining_requests from anon, authenticated;
grant select, insert on table public.dining_requests to anon, authenticated;
grant update (status) on table public.dining_requests to anon, authenticated;
grant usage, select on sequence public.dining_requests_id_seq to anon, authenticated;

drop policy if exists dining_requests_public_insert on public.dining_requests;
create policy dining_requests_public_insert
on public.dining_requests
for insert
to anon, authenticated
with check (
  status = 'new'
  and source in ('table-qr', 'table-service-call')
);

drop policy if exists dining_requests_dashboard_select on public.dining_requests;
create policy dining_requests_dashboard_select
on public.dining_requests
for select
to anon, authenticated
using (true);

drop policy if exists dining_requests_dashboard_status_update on public.dining_requests;
create policy dining_requests_dashboard_status_update
on public.dining_requests
for update
to anon, authenticated
using (true)
with check (
  status in ('new', 'acknowledged', 'preparing', 'ready', 'completed', 'canceled')
);

comment on table public.dining_requests is
  'Guest table orders and service calls consumed by the Queen floor dashboard.';

commit;
