-- EHWA Party / Table / Guest architecture.
-- Run after:
--   1. dining-requests-schema.sql
--   2. dining-qr-sessions-schema.sql
--   3. dining-qr-table-assignment.sql
--
-- This migration preserves the existing live queue. Any currently active
-- QR/table session becomes a one-table active Party automatically.

begin;

create extension if not exists pgcrypto;

create table if not exists public.dining_parties (
  id bigint generated by default as identity primary key,
  branch text not null,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_reason text not null default '',
  updated_at timestamptz not null default now(),
  constraint dining_parties_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_parties_status_check
    check (status in ('ACTIVE', 'CLOSED', 'VOID')),
  constraint dining_parties_closed_check
    check (
      (status = 'ACTIVE' and closed_at is null)
      or
      (status in ('CLOSED', 'VOID') and closed_at is not null)
    )
);

create table if not exists public.dining_tables (
  id bigint generated by default as identity primary key,
  branch text not null,
  table_code text not null,
  qr_number integer,
  current_party_id bigint references public.dining_parties (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dining_tables_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_tables_code_check
    check (char_length(trim(table_code)) between 1 and 40),
  constraint dining_tables_qr_check
    check (qr_number is null or qr_number between 1 and 10),
  constraint dining_tables_branch_code_unique
    unique (branch, table_code)
);

create unique index if not exists dining_tables_branch_code_ci_unique
  on public.dining_tables (branch, lower(table_code));

create unique index if not exists dining_tables_branch_qr_unique
  on public.dining_tables (branch, qr_number)
  where qr_number is not null;

create index if not exists dining_tables_current_party_idx
  on public.dining_tables (current_party_id)
  where current_party_id is not null;

create table if not exists public.dining_party_tables (
  id bigint generated by default as identity primary key,
  party_id bigint not null references public.dining_parties (id) on delete restrict,
  table_id bigint not null references public.dining_tables (id) on delete restrict,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  constraint dining_party_tables_time_check
    check (left_at is null or left_at >= joined_at)
);

create unique index if not exists dining_party_tables_one_active_table
  on public.dining_party_tables (table_id)
  where left_at is null;

create index if not exists dining_party_tables_party_history_idx
  on public.dining_party_tables (party_id, joined_at desc);

create table if not exists public.dining_guests (
  id uuid primary key default gen_random_uuid(),
  branch text not null,
  display_code text not null,
  party_id bigint not null references public.dining_parties (id) on delete restrict,
  current_table_id bigint references public.dining_tables (id) on delete set null,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '10 hours'),
  paid_at timestamptz,
  last_seen_at timestamptz not null default now(),
  current_page text not null default '',
  device_info jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint dining_guests_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_guests_display_code_check
    check (display_code ~ '^[A-Z2-9]{4,6}$'),
  constraint dining_guests_status_check
    check (status in ('ACTIVE', 'PAID', 'EXPIRED', 'VOID')),
  constraint dining_guests_device_info_check
    check (jsonb_typeof(device_info) = 'object'),
  constraint dining_guests_expiry_check
    check (expires_at > created_at),
  constraint dining_guests_paid_check
    check (
      (status = 'PAID' and paid_at is not null)
      or
      (status <> 'PAID')
    ),
  constraint dining_guests_branch_display_unique
    unique (branch, display_code)
);

create index if not exists dining_guests_party_status_idx
  on public.dining_guests (party_id, status, created_at);

create index if not exists dining_guests_expiry_idx
  on public.dining_guests (status, expires_at)
  where status = 'ACTIVE';

alter table public.dining_requests
  add column if not exists party_id bigint,
  add column if not exists guest_id uuid,
  add column if not exists table_id bigint,
  add column if not exists added_by text not null default 'guest';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_requests_party_fk'
      and conrelid = 'public.dining_requests'::regclass
  ) then
    alter table public.dining_requests
      add constraint dining_requests_party_fk
      foreign key (party_id)
      references public.dining_parties (id)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_requests_guest_fk'
      and conrelid = 'public.dining_requests'::regclass
  ) then
    alter table public.dining_requests
      add constraint dining_requests_guest_fk
      foreign key (guest_id)
      references public.dining_guests (id)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_requests_table_fk'
      and conrelid = 'public.dining_requests'::regclass
  ) then
    alter table public.dining_requests
      add constraint dining_requests_table_fk
      foreign key (table_id)
      references public.dining_tables (id)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_requests_added_by_check'
      and conrelid = 'public.dining_requests'::regclass
  ) then
    alter table public.dining_requests
      add constraint dining_requests_added_by_check
      check (added_by in ('guest', 'staff', 'system'));
  end if;
end;
$$;

create index if not exists dining_requests_guest_created_idx
  on public.dining_requests (guest_id, created_at desc)
  where guest_id is not null;

create index if not exists dining_requests_party_created_idx
  on public.dining_requests (party_id, created_at desc)
  where party_id is not null;

create index if not exists dining_requests_table_created_idx
  on public.dining_requests (table_id, created_at desc)
  where table_id is not null;

create table if not exists public.dining_order_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.dining_requests (id) on delete restrict,
  guest_id uuid not null references public.dining_guests (id) on delete restrict,
  party_id bigint not null references public.dining_parties (id) on delete restrict,
  table_id bigint not null references public.dining_tables (id) on delete restrict,
  menu_id text not null,
  name_ko text not null default '',
  name_en text not null default '',
  quantity integer not null,
  unit_price numeric(10, 2) not null,
  line_total numeric(10, 2) not null,
  status text not null default 'new',
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dining_order_items_menu_id_check
    check (char_length(trim(menu_id)) between 1 and 120),
  constraint dining_order_items_quantity_check
    check (quantity between 1 and 50),
  constraint dining_order_items_price_check
    check (unit_price >= 0 and line_total >= 0),
  constraint dining_order_items_status_check
    check (status in ('new', 'acknowledged', 'preparing', 'ready', 'completed', 'canceled'))
);

create index if not exists dining_order_items_guest_created_idx
  on public.dining_order_items (guest_id, created_at desc);

create index if not exists dining_order_items_request_idx
  on public.dining_order_items (request_id, id);

create table if not exists public.dining_order_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.dining_requests (id) on delete restrict,
  order_item_id bigint references public.dining_order_items (id) on delete restrict,
  event_type text not null,
  previous_value jsonb not null default '{}'::jsonb,
  next_value jsonb not null default '{}'::jsonb,
  note text not null default '',
  actor text not null default 'system',
  created_at timestamptz not null default now(),
  constraint dining_order_events_type_check
    check (event_type in ('CREATED', 'STATUS_CHANGED', 'QUANTITY_CHANGED', 'NOTE_ADDED', 'CANCELED')),
  constraint dining_order_events_actor_check
    check (actor in ('guest', 'staff', 'system'))
);

create index if not exists dining_order_events_request_created_idx
  on public.dining_order_events (request_id, created_at);

create table if not exists public.dining_guest_events (
  id bigint generated by default as identity primary key,
  guest_id uuid not null references public.dining_guests (id) on delete restrict,
  event_type text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint dining_guest_events_type_check
    check (event_type in ('CREATED', 'PAGE_CHANGED', 'PAID', 'EXPIRED', 'VOID'))
);

create index if not exists dining_guest_events_guest_created_idx
  on public.dining_guest_events (guest_id, created_at desc);

create table if not exists public.dining_notifications (
  id bigint generated by default as identity primary key,
  branch text not null,
  party_id bigint references public.dining_parties (id) on delete restrict,
  guest_id uuid references public.dining_guests (id) on delete restrict,
  table_id bigint references public.dining_tables (id) on delete restrict,
  request_id bigint references public.dining_requests (id) on delete restrict,
  notification_type text not null,
  title text not null,
  message text not null default '',
  status text not null default 'UNREAD',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '10 hours'),
  read_at timestamptz,
  constraint dining_notifications_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_notifications_type_check
    check (notification_type in (
      'ORDER_ACCEPTED',
      'COOKING',
      'READY',
      'STAFF_COMING',
      'ITEM_UNAVAILABLE',
      'TABLE_MESSAGE',
      'ORDER_SERVED'
    )),
  constraint dining_notifications_status_check
    check (status in ('UNREAD', 'READ'))
);

create index if not exists dining_notifications_guest_unread_idx
  on public.dining_notifications (guest_id, status, created_at)
  where status = 'UNREAD';

create or replace function public.set_dining_architecture_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists dining_parties_set_updated_at on public.dining_parties;
create trigger dining_parties_set_updated_at
before update on public.dining_parties
for each row execute function public.set_dining_architecture_updated_at();

drop trigger if exists dining_tables_set_updated_at on public.dining_tables;
create trigger dining_tables_set_updated_at
before update on public.dining_tables
for each row execute function public.set_dining_architecture_updated_at();

drop trigger if exists dining_guests_set_updated_at on public.dining_guests;
create trigger dining_guests_set_updated_at
before update on public.dining_guests
for each row execute function public.set_dining_architecture_updated_at();

drop trigger if exists dining_order_items_set_updated_at on public.dining_order_items;
create trigger dining_order_items_set_updated_at
before update on public.dining_order_items
for each row execute function public.set_dining_architecture_updated_at();

create or replace function public.create_dining_guest_display_code(
  p_branch text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  candidate text;
  attempt integer;
begin
  for attempt in 1..80 loop
    candidate :=
      substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1)
      || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1)
      || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1)
      || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1);

    if not exists (
      select 1
      from public.dining_guests as guest
      where guest.branch = p_branch
        and guest.display_code = candidate
    ) then
      return candidate;
    end if;
  end loop;

  raise exception 'Could not allocate a guest display code';
end;
$$;

create or replace function public.assign_dining_table_qr(
  p_branch text,
  p_table_code text,
  p_qr_number integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_table_code text := trim(p_table_code);
  target_table public.dining_tables;
  conflicting_table public.dining_tables;
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if normalized_table_code is null or char_length(normalized_table_code) not between 1 and 40 then
    raise exception 'Invalid table code';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'Invalid QR number';
  end if;

  perform pg_advisory_xact_lock(hashtext('table-qr:' || normalized_branch));

  select table_record.*
  into target_table
  from public.dining_tables as table_record
  where table_record.branch = normalized_branch
    and lower(table_record.table_code) = lower(normalized_table_code)
  for update;

  if found and target_table.current_party_id is not null then
    raise exception 'Table % belongs to an active party', target_table.table_code;
  end if;

  select table_record.*
  into conflicting_table
  from public.dining_tables as table_record
  where table_record.branch = normalized_branch
    and table_record.qr_number = p_qr_number
    and lower(table_record.table_code) <> lower(normalized_table_code)
  for update;

  if found then
    if conflicting_table.current_party_id is not null then
      raise exception 'QR % belongs to an active party at Table %', p_qr_number, conflicting_table.table_code;
    end if;
    update public.dining_tables
    set qr_number = null
    where id = conflicting_table.id;
  end if;

  if target_table.id is null then
    insert into public.dining_tables (branch, table_code, qr_number)
    values (normalized_branch, normalized_table_code, p_qr_number)
    returning * into target_table;
  else
    update public.dining_tables
    set qr_number = p_qr_number
    where id = target_table.id
    returning * into target_table;
  end if;

  update public.dining_qr_sessions
  set status = 'closed',
      ended_at = coalesce(ended_at, now()),
      ended_reason = 'permanent-table-qr-remap'
  where branch = normalized_branch
    and status = 'active'
    and (
      qr_number = p_qr_number
      or lower(table_code) = lower(normalized_table_code)
    );

  return jsonb_build_object(
    'id', target_table.id,
    'branch', target_table.branch,
    'table_code', target_table.table_code,
    'qr_number', target_table.qr_number,
    'current_party_id', target_table.current_party_id
  );
end;
$$;

create or replace function public.start_dining_party(
  p_branch text,
  p_table_codes text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_codes text[];
  new_party public.dining_parties;
  selected_count integer;
  code_count integer;
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;

  select array_agg(distinct trim(selected.code))
  into normalized_codes
  from unnest(coalesce(p_table_codes, array[]::text[])) as selected(code)
  where nullif(trim(selected.code), '') is not null;

  code_count := coalesce(array_length(normalized_codes, 1), 0);
  if code_count < 1 or code_count > 30 then
    raise exception 'Select between 1 and 30 tables';
  end if;

  perform pg_advisory_xact_lock(hashtext('party:' || normalized_branch));

  select count(*)
  into selected_count
  from public.dining_tables as table_record
  where table_record.branch = normalized_branch
    and lower(table_record.table_code) = any (
      select lower(selected.code) from unnest(normalized_codes) as selected(code)
    )
    and table_record.qr_number is not null
    and table_record.current_party_id is null;

  if selected_count <> code_count then
    raise exception 'Every selected table needs an assigned QR and must be available';
  end if;

  insert into public.dining_parties (branch)
  values (normalized_branch)
  returning * into new_party;

  update public.dining_tables
  set current_party_id = new_party.id
  where branch = normalized_branch
    and lower(table_code) = any (
      select lower(selected.code) from unnest(normalized_codes) as selected(code)
    );

  insert into public.dining_party_tables (party_id, table_id)
  select new_party.id, table_record.id
  from public.dining_tables as table_record
  where table_record.current_party_id = new_party.id;

  update public.dining_qr_sessions
  set status = 'closed',
      ended_at = coalesce(ended_at, now()),
      ended_reason = 'party-restarted'
  where branch = normalized_branch
    and status = 'active'
    and (
      qr_number in (
        select table_record.qr_number
        from public.dining_tables as table_record
        where table_record.current_party_id = new_party.id
      )
      or lower(table_code) in (
        select lower(table_record.table_code)
        from public.dining_tables as table_record
        where table_record.current_party_id = new_party.id
      )
    );

  insert into public.dining_qr_sessions (branch, qr_number, table_code)
  select table_record.branch, table_record.qr_number, table_record.table_code
  from public.dining_tables as table_record
  where table_record.current_party_id = new_party.id;

  return jsonb_build_object(
    'party_id', new_party.id,
    'status', new_party.status,
    'created_at', new_party.created_at,
    'table_codes', normalized_codes
  );
end;
$$;

create or replace function public.add_dining_tables_to_party(
  p_branch text,
  p_party_id bigint,
  p_table_codes text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_codes text[];
  active_party public.dining_parties;
  selected_count integer;
  code_count integer;
begin
  select party.*
  into active_party
  from public.dining_parties as party
  where party.id = p_party_id
    and party.branch = normalized_branch
    and party.status = 'ACTIVE'
  for update;

  if not found then
    raise exception 'Active party not found';
  end if;

  select array_agg(distinct trim(selected.code))
  into normalized_codes
  from unnest(coalesce(p_table_codes, array[]::text[])) as selected(code)
  where nullif(trim(selected.code), '') is not null;

  code_count := coalesce(array_length(normalized_codes, 1), 0);
  if code_count < 1 or code_count > 30 then
    raise exception 'Select between 1 and 30 tables';
  end if;

  perform pg_advisory_xact_lock(hashtext('party:' || normalized_branch));

  select count(*)
  into selected_count
  from public.dining_tables as table_record
  where table_record.branch = normalized_branch
    and lower(table_record.table_code) = any (
      select lower(selected.code) from unnest(normalized_codes) as selected(code)
    )
    and table_record.qr_number is not null
    and table_record.current_party_id is null;

  if selected_count <> code_count then
    raise exception 'Every selected table needs an assigned QR and must be available';
  end if;

  update public.dining_tables
  set current_party_id = active_party.id
  where branch = normalized_branch
    and lower(table_code) = any (
      select lower(selected.code) from unnest(normalized_codes) as selected(code)
    );

  insert into public.dining_party_tables (party_id, table_id)
  select active_party.id, table_record.id
  from public.dining_tables as table_record
  where table_record.current_party_id = active_party.id
    and lower(table_record.table_code) = any (
      select lower(selected.code) from unnest(normalized_codes) as selected(code)
    );

  insert into public.dining_qr_sessions (branch, qr_number, table_code)
  select table_record.branch, table_record.qr_number, table_record.table_code
  from public.dining_tables as table_record
  where table_record.current_party_id = active_party.id
    and lower(table_record.table_code) = any (
      select lower(selected.code) from unnest(normalized_codes) as selected(code)
    );

  return jsonb_build_object(
    'party_id', active_party.id,
    'table_codes', normalized_codes
  );
end;
$$;

create or replace function public.close_dining_party(
  p_branch text,
  p_party_id bigint,
  p_reason text default 'table-checkout'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  active_party public.dining_parties;
begin
  select party.*
  into active_party
  from public.dining_parties as party
  where party.id = p_party_id
    and party.branch = normalized_branch
    and party.status = 'ACTIVE'
  for update;

  if not found then
    raise exception 'Active party not found';
  end if;

  update public.dining_qr_sessions as session
  set status = 'closed',
      ended_at = coalesce(session.ended_at, now()),
      ended_reason = left(coalesce(nullif(trim(p_reason), ''), 'party-closed'), 80)
  where session.branch = normalized_branch
    and session.status = 'active'
    and exists (
      select 1
      from public.dining_tables as table_record
      where table_record.current_party_id = active_party.id
        and (
          table_record.qr_number = session.qr_number
          or lower(table_record.table_code) = lower(session.table_code)
        )
    );

  update public.dining_requests
  set status = 'canceled'
  where party_id = active_party.id
    and status not in ('completed', 'canceled');

  update public.dining_guests
  set status = 'EXPIRED',
      expires_at = greatest(created_at + interval '1 second', now())
  where party_id = active_party.id
    and status = 'ACTIVE';

  insert into public.dining_guest_events (guest_id, event_type, detail)
  select guest.id, 'EXPIRED', jsonb_build_object('reason', 'party-closed')
  from public.dining_guests as guest
  where guest.party_id = active_party.id
    and guest.status = 'EXPIRED'
    and not exists (
      select 1
      from public.dining_guest_events as event
      where event.guest_id = guest.id
        and event.event_type = 'EXPIRED'
    );

  update public.dining_party_tables
  set left_at = now()
  where party_id = active_party.id
    and left_at is null;

  update public.dining_tables
  set current_party_id = null
  where current_party_id = active_party.id;

  update public.dining_parties
  set status = 'CLOSED',
      closed_at = now(),
      closed_reason = left(coalesce(nullif(trim(p_reason), ''), 'party-closed'), 80)
  where id = active_party.id;

  return jsonb_build_object(
    'party_id', active_party.id,
    'status', 'CLOSED'
  );
end;
$$;

create or replace function public.resolve_dining_guest(
  p_branch text,
  p_qr_number integer,
  p_guest_id uuid default null,
  p_device_info jsonb default '{}'::jsonb,
  p_current_page text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  active_table public.dining_tables;
  active_party public.dining_parties;
  resolved_guest public.dining_guests;
  compatibility_session_id bigint;
  safe_device_info jsonb := coalesce(p_device_info, '{}'::jsonb);
  safe_page text := left(coalesce(p_current_page, ''), 300);
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'Invalid QR number';
  end if;
  if jsonb_typeof(safe_device_info) <> 'object'
    or octet_length(safe_device_info::text) > 12000
  then
    safe_device_info := '{}'::jsonb;
  end if;

  update public.dining_guests
  set status = 'EXPIRED'
  where status = 'ACTIVE'
    and expires_at <= now();

  select table_record.*
  into active_table
  from public.dining_tables as table_record
  join public.dining_parties as party
    on party.id = table_record.current_party_id
   and party.status = 'ACTIVE'
  where table_record.branch = normalized_branch
    and table_record.qr_number = p_qr_number
  limit 1;

  if not found then
    raise exception 'This QR is not assigned to an active party';
  end if;

  select party.*
  into active_party
  from public.dining_parties as party
  where party.id = active_table.current_party_id
    and party.status = 'ACTIVE';

  if p_guest_id is not null then
    select guest.*
    into resolved_guest
    from public.dining_guests as guest
    where guest.id = p_guest_id
      and guest.branch = normalized_branch
      and guest.party_id = active_party.id
      and guest.status = 'ACTIVE'
      and guest.expires_at > now()
    for update;
  end if;

  if resolved_guest.id is null then
    insert into public.dining_guests (
      branch,
      display_code,
      party_id,
      current_table_id,
      device_info,
      current_page
    )
    values (
      normalized_branch,
      public.create_dining_guest_display_code(normalized_branch),
      active_party.id,
      active_table.id,
      safe_device_info,
      safe_page
    )
    returning * into resolved_guest;

    insert into public.dining_guest_events (guest_id, event_type, detail)
    values (
      resolved_guest.id,
      'CREATED',
      jsonb_build_object(
        'party_id', active_party.id,
        'table_id', active_table.id,
        'table_code', active_table.table_code
      )
    );
  else
    if resolved_guest.current_page is distinct from safe_page then
      insert into public.dining_guest_events (guest_id, event_type, detail)
      values (
        resolved_guest.id,
        'PAGE_CHANGED',
        jsonb_build_object(
          'from', resolved_guest.current_page,
          'to', safe_page,
          'table_code', active_table.table_code
        )
      );
    end if;

    update public.dining_guests
    set last_seen_at = now(),
        current_table_id = active_table.id,
        current_page = safe_page,
        device_info = case
          when safe_device_info = '{}'::jsonb then device_info
          else safe_device_info
        end
    where id = resolved_guest.id
    returning * into resolved_guest;
  end if;

  select session.id
  into compatibility_session_id
  from public.dining_qr_sessions as session
  where session.branch = normalized_branch
    and session.qr_number = p_qr_number
    and session.status = 'active'
  order by session.started_at desc
  limit 1;

  return jsonb_build_object(
    'guest_id', resolved_guest.id,
    'display_code', resolved_guest.display_code,
    'guest_status', resolved_guest.status,
    'created_at', resolved_guest.created_at,
    'expires_at', resolved_guest.expires_at,
    'party_id', active_party.id,
    'party_status', active_party.status,
    'table_id', active_table.id,
    'table_code', active_table.table_code,
    'qr_number', active_table.qr_number,
    'qr_session_id', compatibility_session_id
  );
end;
$$;

create or replace function public.validate_dining_request_qr_session()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  active_session public.dining_qr_sessions;
  active_guest public.dining_guests;
  active_table public.dining_tables;
begin
  if new.guest_id is not null then
    select guest.*
    into active_guest
    from public.dining_guests as guest
    where guest.id = new.guest_id
      and guest.branch = new.branch
      and guest.status = 'ACTIVE'
      and guest.expires_at > now();

    if not found then
      raise exception 'An active Guest is required';
    end if;

    select table_record.*
    into active_table
    from public.dining_tables as table_record
    join public.dining_parties as party
      on party.id = table_record.current_party_id
     and party.status = 'ACTIVE'
    where table_record.id = new.table_id
      and table_record.branch = new.branch
      and table_record.current_party_id = active_guest.party_id;

    if not found then
      raise exception 'The Table does not belong to the Guest Party';
    end if;

    new.party_id = active_guest.party_id;
    new.table_id = active_table.id;
    new.table_code = active_table.table_code;
    new.qr_number = active_table.qr_number;
    return new;
  end if;

  if new.qr_session_id is null or new.qr_number is null then
    raise exception 'An active QR session or Guest is required';
  end if;

  select session.*
  into active_session
  from public.dining_qr_sessions as session
  where session.id = new.qr_session_id
    and session.branch = new.branch
    and session.qr_number = new.qr_number
    and session.status = 'active'
    and nullif(trim(session.table_code), '') is not null;

  if not found then
    raise exception 'The QR is not assigned to an active table';
  end if;

  new.table_code = active_session.table_code;
  return new;
end;
$$;

create or replace function public.submit_dining_request_v2(
  p_branch text,
  p_qr_number integer,
  p_guest_id uuid,
  p_kind text,
  p_request_type text,
  p_note text default '',
  p_items jsonb default '[]'::jsonb
)
returns public.dining_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_kind text := lower(trim(p_kind));
  normalized_request_type text := lower(trim(p_request_type));
  active_guest public.dining_guests;
  active_table public.dining_tables;
  new_request public.dining_requests;
  compatibility_session_id bigint;
  calculated_item_count integer := 0;
  calculated_subtotal numeric(10, 2) := 0;
  calculated_tax numeric(10, 2) := 0;
  calculated_total numeric(10, 2) := 0;
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if p_guest_id is null then
    raise exception 'Guest is required';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'Invalid QR number';
  end if;
  if normalized_kind is null or normalized_kind not in ('order', 'service') then
    raise exception 'Invalid request kind';
  end if;
  if normalized_request_type is null or normalized_request_type not in ('order', 'water', 'napkins', 'server') then
    raise exception 'Invalid request type';
  end if;
  if p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) > 60
    or octet_length(p_items::text) > 120000
  then
    raise exception 'Invalid order items';
  end if;

  select guest.*
  into active_guest
  from public.dining_guests as guest
  join public.dining_parties as party
    on party.id = guest.party_id
   and party.status = 'ACTIVE'
  where guest.id = p_guest_id
    and guest.branch = normalized_branch
    and guest.status = 'ACTIVE'
    and guest.expires_at > now()
  for update;

  if not found then
    raise exception 'Guest is no longer active';
  end if;

  select table_record.*
  into active_table
  from public.dining_tables as table_record
  where table_record.branch = normalized_branch
    and table_record.qr_number = p_qr_number
    and table_record.current_party_id = active_guest.party_id;

  if not found then
    raise exception 'This Table does not belong to the Guest Party';
  end if;

  if normalized_kind = 'order' then
    if normalized_request_type <> 'order' or jsonb_array_length(p_items) < 1 then
      raise exception 'An order requires one or more menu items';
    end if;

    if exists (
      select 1
      from jsonb_array_elements(p_items) as element(item)
      where nullif(trim(element.item->>'menuId'), '') is null
        or coalesce(element.item->>'quantity', '') !~ '^[0-9]+$'
        or (element.item->>'quantity')::integer not between 1 and 50
        or coalesce(element.item->>'unitPrice', '') !~ '^[0-9]+([.][0-9]{1,2})?$'
        or (element.item->>'unitPrice')::numeric < 0
        or (element.item->>'unitPrice')::numeric > 9999.99
    ) then
      raise exception 'One or more menu items are invalid';
    end if;

    select
      coalesce(sum((element.item->>'quantity')::integer), 0),
      coalesce(sum(
        (element.item->>'quantity')::integer
        * (element.item->>'unitPrice')::numeric
      ), 0)
    into calculated_item_count, calculated_subtotal
    from jsonb_array_elements(p_items) as element(item);

    calculated_subtotal := round(calculated_subtotal, 2);
    calculated_tax := round(calculated_subtotal * 0.13, 2);
    calculated_total := calculated_subtotal + calculated_tax;
    if calculated_item_count > 100 then
      raise exception 'An order cannot contain more than 100 items';
    end if;
  else
    if normalized_request_type = 'order' or jsonb_array_length(p_items) <> 0 then
      raise exception 'A service request cannot contain menu items';
    end if;
  end if;

  select session.id
  into compatibility_session_id
  from public.dining_qr_sessions as session
  where session.branch = normalized_branch
    and session.qr_number = p_qr_number
    and session.status = 'active'
  order by session.started_at desc
  limit 1;

  insert into public.dining_requests (
    branch,
    table_code,
    guest_count,
    kind,
    request_type,
    status,
    source,
    qr_number,
    qr_session_id,
    party_id,
    guest_id,
    table_id,
    added_by,
    note,
    items,
    item_count,
    subtotal,
    tax,
    total
  )
  values (
    normalized_branch,
    active_table.table_code,
    1,
    normalized_kind,
    normalized_request_type,
    'new',
    case when normalized_kind = 'order' then 'table-qr' else 'table-service-call' end,
    p_qr_number,
    compatibility_session_id,
    active_guest.party_id,
    active_guest.id,
    active_table.id,
    'guest',
    left(coalesce(p_note, ''), 1000),
    p_items,
    calculated_item_count,
    calculated_subtotal,
    calculated_tax,
    calculated_total
  )
  returning * into new_request;

  if normalized_kind = 'order' then
    insert into public.dining_order_items (
      request_id,
      guest_id,
      party_id,
      table_id,
      menu_id,
      name_ko,
      name_en,
      quantity,
      unit_price,
      line_total,
      note
    )
    select
      new_request.id,
      active_guest.id,
      active_guest.party_id,
      active_table.id,
      left(trim(element.item->>'menuId'), 120),
      left(coalesce(element.item->>'nameKo', ''), 200),
      left(coalesce(element.item->>'nameEn', ''), 200),
      (element.item->>'quantity')::integer,
      round((element.item->>'unitPrice')::numeric, 2),
      round(
        (element.item->>'quantity')::integer
        * (element.item->>'unitPrice')::numeric,
        2
      ),
      left(coalesce(element.item->>'note', ''), 500)
    from jsonb_array_elements(p_items) as element(item);
  end if;

  insert into public.dining_order_events (
    request_id,
    event_type,
    next_value,
    actor
  )
  values (
    new_request.id,
    'CREATED',
    jsonb_build_object(
      'status', new_request.status,
      'table_id', active_table.id,
      'table_code', active_table.table_code,
      'guest_id', active_guest.id
    ),
    'guest'
  );

  update public.dining_guests
  set last_seen_at = now(),
      current_page = '/test/menu/'
  where id = active_guest.id;

  return new_request;
end;
$$;

create or replace function public.sync_dining_order_status_and_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  notification_type text;
  notification_title text;
  notification_message text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  update public.dining_order_items
  set status = new.status
  where request_id = new.id;

  insert into public.dining_order_events (
    request_id,
    event_type,
    previous_value,
    next_value,
    actor
  )
  values (
    new.id,
    case when new.status = 'canceled' then 'CANCELED' else 'STATUS_CHANGED' end,
    jsonb_build_object('status', old.status),
    jsonb_build_object('status', new.status),
    'staff'
  );

  if new.guest_id is not null then
    if new.status in ('acknowledged', 'preparing') then
      notification_type := 'COOKING';
      notification_title := case when new.kind = 'order' then 'Order accepted' else 'Staff is coming' end;
      notification_message := case when new.kind = 'order' then 'Your order is being prepared.' else 'A staff member is on the way.' end;
    elsif new.status = 'ready' then
      notification_type := 'READY';
      notification_title := 'Order ready';
      notification_message := 'Your order is ready.';
    elsif new.status = 'completed' then
      notification_type := 'ORDER_SERVED';
      notification_title := case when new.kind = 'order' then 'Order served' else 'Request completed' end;
      notification_message := case when new.kind = 'order' then 'This order has been served.' else 'Your request has been completed.' end;
    elsif new.status = 'canceled' then
      notification_type := 'ITEM_UNAVAILABLE';
      notification_title := 'Order update';
      notification_message := 'Please ask a staff member about this canceled request.';
    end if;

    if notification_type is not null then
      insert into public.dining_notifications (
        branch,
        party_id,
        guest_id,
        table_id,
        request_id,
        notification_type,
        title,
        message
      )
      values (
        new.branch,
        new.party_id,
        new.guest_id,
        new.table_id,
        new.id,
        notification_type,
        notification_title,
        notification_message
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists dining_requests_sync_order_status on public.dining_requests;
create trigger dining_requests_sync_order_status
after update of status on public.dining_requests
for each row
execute function public.sync_dining_order_status_and_notify();

create or replace function public.get_dining_guest_notifications(
  p_branch text,
  p_guest_id uuid
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(to_jsonb(notification_row) order by notification_row.created_at),
    '[]'::jsonb
  )
  from (
    select
      notification.id,
      notification.notification_type,
      notification.title,
      notification.message,
      notification.request_id,
      notification.created_at
    from public.dining_notifications as notification
    join public.dining_guests as guest
      on guest.id = p_guest_id
     and guest.branch = lower(trim(p_branch))
    where notification.branch = lower(trim(p_branch))
      and (
        notification.guest_id = p_guest_id
        or (
          notification.guest_id is null
          and notification.party_id = guest.party_id
          and notification.table_id is null
        )
        or (
          notification.guest_id is null
          and notification.table_id = guest.current_table_id
        )
      )
      and notification.status = 'UNREAD'
      and notification.expires_at > now()
      and guest.status in ('ACTIVE', 'PAID')
    order by notification.created_at
    limit 20
  ) as notification_row;
$$;

create or replace function public.send_dining_notification(
  p_branch text,
  p_notification_type text,
  p_title text,
  p_message text default '',
  p_party_id bigint default null,
  p_guest_id uuid default null,
  p_table_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_type text := upper(trim(p_notification_type));
  notification_id bigint;
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if normalized_type is null or normalized_type not in (
    'ORDER_ACCEPTED',
    'COOKING',
    'READY',
    'STAFF_COMING',
    'ITEM_UNAVAILABLE',
    'TABLE_MESSAGE',
    'ORDER_SERVED'
  ) then
    raise exception 'Invalid notification type';
  end if;
  if nullif(trim(p_title), '') is null then
    raise exception 'Notification title is required';
  end if;
  if p_party_id is null and p_guest_id is null and p_table_id is null then
    raise exception 'A Party, Guest, or Table target is required';
  end if;

  insert into public.dining_notifications (
    branch,
    party_id,
    guest_id,
    table_id,
    notification_type,
    title,
    message
  )
  values (
    normalized_branch,
    p_party_id,
    p_guest_id,
    p_table_id,
    normalized_type,
    left(trim(p_title), 160),
    left(coalesce(p_message, ''), 1000)
  )
  returning id into notification_id;

  return notification_id;
end;
$$;

create or replace function public.read_dining_guest_notifications(
  p_branch text,
  p_guest_id uuid,
  p_notification_ids bigint[]
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
begin
  update public.dining_notifications as notification
  set status = 'READ',
      read_at = now()
  from public.dining_guests as guest
  where guest.id = p_guest_id
    and guest.branch = lower(trim(p_branch))
    and notification.branch = guest.branch
    and (
      notification.guest_id = guest.id
      or (
        notification.guest_id is null
        and notification.party_id = guest.party_id
        and notification.table_id is null
      )
      or (
        notification.guest_id is null
        and notification.table_id = guest.current_table_id
      )
    )
    and notification.status = 'UNREAD'
    and notification.id = any(coalesce(p_notification_ids, array[]::bigint[]));

  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

create or replace function public.get_dining_admin_snapshot(
  p_branch text
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'parties',
    (
      select coalesce(
        jsonb_agg(to_jsonb(party_row) order by party_row.created_at desc),
        '[]'::jsonb
      )
      from (
        select party.*
        from public.dining_parties as party
        where party.branch = lower(trim(p_branch))
          and party.status = 'ACTIVE'
        order by party.created_at desc
        limit 200
      ) as party_row
    ),
    'tables',
    (
      select coalesce(
        jsonb_agg(to_jsonb(table_row) order by table_row.table_code),
        '[]'::jsonb
      )
      from (
        select table_record.*
        from public.dining_tables as table_record
        where table_record.branch = lower(trim(p_branch))
      ) as table_row
    ),
    'party_tables',
    (
      select coalesce(
        jsonb_agg(to_jsonb(party_table_row) order by party_table_row.joined_at),
        '[]'::jsonb
      )
      from (
        select
          party_table.id,
          party_table.party_id,
          party_table.table_id,
          table_record.table_code,
          table_record.qr_number,
          party_table.joined_at,
          party_table.left_at
        from public.dining_party_tables as party_table
        join public.dining_tables as table_record
          on table_record.id = party_table.table_id
        join public.dining_parties as party
          on party.id = party_table.party_id
        where party.branch = lower(trim(p_branch))
          and party.status = 'ACTIVE'
      ) as party_table_row
    ),
    'guests',
    (
      select coalesce(
        jsonb_agg(to_jsonb(guest_row) order by guest_row.created_at),
        '[]'::jsonb
      )
      from (
        select guest.*
        from public.dining_guests as guest
        join public.dining_parties as party
          on party.id = guest.party_id
        where guest.branch = lower(trim(p_branch))
          and party.status = 'ACTIVE'
      ) as guest_row
    ),
    'orders',
    (
      select coalesce(
        jsonb_agg(to_jsonb(order_row) order by order_row.created_at desc),
        '[]'::jsonb
      )
      from (
        select
          request.id,
          request.party_id,
          request.guest_id,
          request.table_id,
          request.table_code,
          request.kind,
          request.request_type,
          request.status,
          request.note,
          request.items,
          request.item_count,
          request.subtotal,
          request.tax,
          request.total,
          request.added_by,
          request.created_at,
          request.updated_at
        from public.dining_requests as request
        join public.dining_parties as party
          on party.id = request.party_id
        where request.branch = lower(trim(p_branch))
          and party.status = 'ACTIVE'
          and request.guest_id is not null
        order by request.created_at desc
        limit 3000
      ) as order_row
    ),
    'order_events',
    (
      select coalesce(
        jsonb_agg(to_jsonb(event_row) order by event_row.created_at),
        '[]'::jsonb
      )
      from (
        select event.*
        from public.dining_order_events as event
        join public.dining_requests as request
          on request.id = event.request_id
        join public.dining_parties as party
          on party.id = request.party_id
        where request.branch = lower(trim(p_branch))
          and party.status = 'ACTIVE'
        order by event.created_at
        limit 10000
      ) as event_row
    ),
    'guest_events',
    (
      select coalesce(
        jsonb_agg(to_jsonb(event_row) order by event_row.created_at),
        '[]'::jsonb
      )
      from (
        select event.*
        from public.dining_guest_events as event
        join public.dining_guests as guest
          on guest.id = event.guest_id
        join public.dining_parties as party
          on party.id = guest.party_id
        where guest.branch = lower(trim(p_branch))
          and party.status = 'ACTIVE'
        order by event.created_at
        limit 10000
      ) as event_row
    )
  );
$$;

create or replace function public.lookup_dining_guest_bill(
  p_branch text,
  p_guest_id uuid default null,
  p_display_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_branch text := lower(trim(p_branch));
  normalized_code text := upper(trim(coalesce(p_display_code, '')));
  target_guest public.dining_guests;
  party_tables jsonb;
  guest_orders jsonb;
  guest_total numeric(10, 2);
begin
  select guest.*
  into target_guest
  from public.dining_guests as guest
  where guest.branch = normalized_branch
    and (
      (p_guest_id is not null and guest.id = p_guest_id)
      or
      (p_guest_id is null and normalized_code <> '' and guest.display_code = normalized_code)
    )
  order by guest.created_at desc
  limit 1;

  if not found then
    raise exception 'Guest not found';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'table_id', table_record.id,
        'table_code', table_record.table_code,
        'qr_number', table_record.qr_number
      )
      order by table_record.table_code
    ),
    '[]'::jsonb
  )
  into party_tables
  from public.dining_party_tables as party_table
  join public.dining_tables as table_record
    on table_record.id = party_table.table_id
  where party_table.party_id = target_guest.party_id;

  select
    coalesce(
      jsonb_agg(to_jsonb(order_row) order by order_row.created_at desc),
      '[]'::jsonb
    ),
    coalesce(sum(order_row.total) filter (
      where order_row.kind = 'order'
        and order_row.status <> 'canceled'
    ), 0)
  into guest_orders, guest_total
  from (
    select
      request.id,
      request.table_id,
      request.table_code,
      request.kind,
      request.request_type,
      request.status,
      request.items,
      request.item_count,
      request.subtotal,
      request.tax,
      request.total,
      request.note,
      request.created_at,
      request.updated_at
    from public.dining_requests as request
    where request.guest_id = target_guest.id
    order by request.created_at desc
  ) as order_row;

  return jsonb_build_object(
    'guest', to_jsonb(target_guest),
    'party_id', target_guest.party_id,
    'tables', party_tables,
    'orders', guest_orders,
    'total', guest_total
  );
end;
$$;

create or replace function public.mark_dining_guest_paid(
  p_branch text,
  p_display_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_guest public.dining_guests;
begin
  select guest.*
  into target_guest
  from public.dining_guests as guest
  where guest.branch = lower(trim(p_branch))
    and guest.display_code = upper(trim(p_display_code))
    and guest.status = 'ACTIVE'
  order by guest.created_at desc
  limit 1
  for update;

  if not found then
    raise exception 'Active Guest not found';
  end if;

  update public.dining_guests
  set status = 'PAID',
      paid_at = now(),
      last_seen_at = now()
  where id = target_guest.id;

  insert into public.dining_guest_events (guest_id, event_type, detail)
  values (
    target_guest.id,
    'PAID',
    jsonb_build_object('display_code', target_guest.display_code)
  );

  return public.lookup_dining_guest_bill(
    lower(trim(p_branch)),
    target_guest.id,
    null
  );
end;
$$;

-- Seed permanent Table/QR mappings from the current active sessions.
insert into public.dining_tables (branch, table_code, qr_number)
select
  session.branch,
  session.table_code,
  session.qr_number
from public.dining_qr_sessions as session
where session.status = 'active'
  and nullif(trim(session.table_code), '') is not null
on conflict (branch, table_code)
do update set qr_number = excluded.qr_number;

-- Preserve current service by converting each pre-migration active table
-- session into a one-table Party.
do $$
declare
  session_record record;
  migrated_party_id bigint;
  migrated_table_id bigint;
begin
  for session_record in
    select
      session.branch,
      session.qr_number,
      session.table_code
    from public.dining_qr_sessions as session
    where session.status = 'active'
      and nullif(trim(session.table_code), '') is not null
  loop
    select table_record.id, table_record.current_party_id
    into migrated_table_id, migrated_party_id
    from public.dining_tables as table_record
    where table_record.branch = session_record.branch
      and lower(table_record.table_code) = lower(session_record.table_code)
    for update;

    if migrated_party_id is null then
      insert into public.dining_parties (branch)
      values (session_record.branch)
      returning id into migrated_party_id;

      update public.dining_tables
      set current_party_id = migrated_party_id
      where id = migrated_table_id;

      insert into public.dining_party_tables (party_id, table_id)
      values (migrated_party_id, migrated_table_id);
    end if;
  end loop;
end;
$$;

alter table public.dining_parties enable row level security;
alter table public.dining_tables enable row level security;
alter table public.dining_party_tables enable row level security;
alter table public.dining_guests enable row level security;
alter table public.dining_order_items enable row level security;
alter table public.dining_order_events enable row level security;
alter table public.dining_guest_events enable row level security;
alter table public.dining_notifications enable row level security;

revoke all on table public.dining_parties from anon, authenticated;
revoke all on table public.dining_tables from anon, authenticated;
revoke all on table public.dining_party_tables from anon, authenticated;
revoke all on table public.dining_guests from anon, authenticated;
revoke all on table public.dining_order_items from anon, authenticated;
revoke all on table public.dining_order_events from anon, authenticated;
revoke all on table public.dining_guest_events from anon, authenticated;
revoke all on table public.dining_notifications from anon, authenticated;

revoke all on function public.create_dining_guest_display_code(text) from public;
revoke all on function public.assign_dining_table_qr(text, text, integer) from public;
revoke all on function public.start_dining_party(text, text[]) from public;
revoke all on function public.add_dining_tables_to_party(text, bigint, text[]) from public;
revoke all on function public.close_dining_party(text, bigint, text) from public;
revoke all on function public.resolve_dining_guest(text, integer, uuid, jsonb, text) from public;
revoke all on function public.submit_dining_request_v2(text, integer, uuid, text, text, text, jsonb) from public;
revoke all on function public.get_dining_guest_notifications(text, uuid) from public;
revoke all on function public.send_dining_notification(text, text, text, text, bigint, uuid, bigint) from public;
revoke all on function public.read_dining_guest_notifications(text, uuid, bigint[]) from public;
revoke all on function public.get_dining_admin_snapshot(text) from public;
revoke all on function public.lookup_dining_guest_bill(text, uuid, text) from public;
revoke all on function public.mark_dining_guest_paid(text, text) from public;

grant execute on function public.assign_dining_table_qr(text, text, integer)
  to anon, authenticated;
grant execute on function public.start_dining_party(text, text[])
  to anon, authenticated;
grant execute on function public.add_dining_tables_to_party(text, bigint, text[])
  to anon, authenticated;
grant execute on function public.close_dining_party(text, bigint, text)
  to anon, authenticated;
grant execute on function public.resolve_dining_guest(text, integer, uuid, jsonb, text)
  to anon, authenticated;
grant execute on function public.submit_dining_request_v2(text, integer, uuid, text, text, text, jsonb)
  to anon, authenticated;
grant execute on function public.get_dining_guest_notifications(text, uuid)
  to anon, authenticated;
grant execute on function public.send_dining_notification(text, text, text, text, bigint, uuid, bigint)
  to anon, authenticated;
grant execute on function public.read_dining_guest_notifications(text, uuid, bigint[])
  to anon, authenticated;
grant execute on function public.get_dining_admin_snapshot(text)
  to anon, authenticated;
grant execute on function public.lookup_dining_guest_bill(text, uuid, text)
  to anon, authenticated;
grant execute on function public.mark_dining_guest_paid(text, text)
  to anon, authenticated;

drop policy if exists dining_requests_public_insert on public.dining_requests;
create policy dining_requests_public_insert
on public.dining_requests
for insert
to anon, authenticated
with check (
  status = 'new'
  and source in ('table-qr', 'table-service-call')
  and (
    (
      guest_id is not null
      and party_id is not null
      and table_id is not null
      and exists (
        select 1
        from public.dining_guests as guest
        join public.dining_tables as table_record
          on table_record.id = dining_requests.table_id
        join public.dining_parties as party
          on party.id = guest.party_id
        where guest.id = dining_requests.guest_id
          and guest.branch = dining_requests.branch
          and guest.status = 'ACTIVE'
          and guest.expires_at > now()
          and party.status = 'ACTIVE'
          and table_record.current_party_id = guest.party_id
      )
    )
    or
    (
      qr_number between 1 and 10
      and qr_session_id is not null
      and exists (
        select 1
        from public.dining_qr_sessions as session
        where session.id = dining_requests.qr_session_id
          and session.branch = dining_requests.branch
          and session.qr_number = dining_requests.qr_number
          and session.status = 'active'
          and dining_requests.table_code = session.table_code
      )
    )
  )
);

comment on table public.dining_parties is
  'One active dining group containing one or more physical tables.';
comment on table public.dining_tables is
  'Physical table registry with durable QR-to-table assignment.';
comment on table public.dining_guests is
  'Temporary bill owners. Guest identity is reused only inside the same Party.';
comment on table public.dining_order_items is
  'Normalized menu lines preserving Guest billing and origin Table.';
comment on table public.dining_notifications is
  'Short-lived messages targeted to a Party, Guest, or Table.';

commit;
