-- QR 1-10 guest sessions and durable order history for /test/menu/ and Queen.
-- Run this after dining-requests-schema.sql in the Supabase SQL editor.

begin;

create table if not exists public.dining_qr_sessions (
  id bigint generated by default as identity primary key,
  branch text not null,
  qr_number integer not null,
  table_code text,
  status text not null default 'active',
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  ended_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dining_qr_sessions_branch_check
    check (branch ~ '^[a-z0-9_-]{1,40}$'),
  constraint dining_qr_sessions_number_check
    check (qr_number between 1 and 10),
  constraint dining_qr_sessions_status_check
    check (status in ('active', 'closed')),
  constraint dining_qr_sessions_active_table_check
    check (status = 'closed' or nullif(trim(table_code), '') is not null),
  constraint dining_qr_sessions_end_check
    check (
      (status = 'active' and ended_at is null)
      or
      (status = 'closed' and ended_at is not null)
    )
);

alter table public.dining_qr_sessions
  add column if not exists table_code text;

update public.dining_qr_sessions
set status = 'closed',
    ended_at = coalesce(ended_at, now()),
    ended_reason = coalesce(nullif(ended_reason, ''), 'table-assignment-migration')
where status = 'active'
  and nullif(trim(table_code), '') is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_qr_sessions_active_table_check'
      and conrelid = 'public.dining_qr_sessions'::regclass
  ) then
    alter table public.dining_qr_sessions
      add constraint dining_qr_sessions_active_table_check
      check (status = 'closed' or nullif(trim(table_code), '') is not null);
  end if;
end;
$$;

create unique index if not exists dining_qr_sessions_one_active_idx
  on public.dining_qr_sessions (branch, qr_number)
  where status = 'active';

create index if not exists dining_qr_sessions_history_idx
  on public.dining_qr_sessions (branch, qr_number, started_at desc);

create unique index if not exists dining_qr_sessions_one_active_table
  on public.dining_qr_sessions (branch, lower(table_code))
  where status = 'active';

create index if not exists dining_qr_sessions_table_history
  on public.dining_qr_sessions (branch, lower(table_code), started_at desc);

alter table public.dining_requests
  add column if not exists qr_number integer,
  add column if not exists qr_session_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_requests_qr_number_check'
      and conrelid = 'public.dining_requests'::regclass
  ) then
    alter table public.dining_requests
      add constraint dining_requests_qr_number_check
      check (qr_number is null or qr_number between 1 and 10);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'dining_requests_qr_session_fk'
      and conrelid = 'public.dining_requests'::regclass
  ) then
    alter table public.dining_requests
      add constraint dining_requests_qr_session_fk
      foreign key (qr_session_id)
      references public.dining_qr_sessions (id)
      on delete restrict;
  end if;
end;
$$;

create index if not exists dining_requests_qr_session_created_idx
  on public.dining_requests (qr_session_id, created_at desc);

create index if not exists dining_requests_branch_qr_created_idx
  on public.dining_requests (branch, qr_number, created_at desc);

create or replace function public.set_dining_qr_session_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists dining_qr_sessions_set_updated_at on public.dining_qr_sessions;
create trigger dining_qr_sessions_set_updated_at
before update on public.dining_qr_sessions
for each row
execute function public.set_dining_qr_session_updated_at();

create or replace function public.validate_dining_request_qr_session()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  active_session public.dining_qr_sessions;
begin
  if new.qr_session_id is null or new.qr_number is null then
    raise exception 'An active QR session is required';
  end if;

  select session.*
  into active_session
  from public.dining_qr_sessions as session
  where session.id = new.qr_session_id
    and session.branch = new.branch
    and session.qr_number = new.qr_number
    and session.status = 'active'
    and nullif(trim(session.table_code), '') is not null;

  if not found then
    raise exception 'The QR is not assigned to an active table';
  end if;

  new.table_code = active_session.table_code;
  return new;
end;
$$;

drop trigger if exists dining_requests_validate_qr_session on public.dining_requests;
create trigger dining_requests_validate_qr_session
before insert on public.dining_requests
for each row
execute function public.validate_dining_request_qr_session();

create or replace function public.assign_dining_qr_session(
  p_branch text,
  p_qr_number integer,
  p_table_code text
)
returns public.dining_qr_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  active_session public.dining_qr_sessions;
  normalized_branch text := lower(trim(p_branch));
  normalized_table_code text := trim(p_table_code);
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'QR number must be between 1 and 10';
  end if;
  if normalized_table_code is null or normalized_table_code = '' or length(normalized_table_code) > 40 then
    raise exception 'Table code must be between 1 and 40 characters';
  end if;

  perform pg_advisory_xact_lock(hashtext(normalized_branch));

  select session.*
  into active_session
  from public.dining_qr_sessions as session
  where session.branch = normalized_branch
    and session.qr_number = p_qr_number
    and session.status = 'active'
  limit 1;

  if found then
    if lower(active_session.table_code) = lower(normalized_table_code) then
      return active_session;
    end if;
    raise exception 'QR % is already assigned to table %', p_qr_number, active_session.table_code;
  end if;

  if exists (
    select 1
    from public.dining_qr_sessions as session
    where session.branch = normalized_branch
      and lower(session.table_code) = lower(normalized_table_code)
      and session.status = 'active'
  ) then
    raise exception 'Table % already has an active QR', normalized_table_code;
  end if;

  insert into public.dining_qr_sessions (branch, qr_number, table_code)
  values (normalized_branch, p_qr_number, normalized_table_code)
  returning * into active_session;

  return active_session;
end;
$$;

drop function if exists public.activate_dining_qr_session(text, integer);

create or replace function public.reset_dining_qr_session(
  p_branch text,
  p_qr_number integer
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  active_session_id bigint;
  normalized_branch text := lower(trim(p_branch));
begin
  if normalized_branch is null or normalized_branch !~ '^[a-z0-9_-]{1,40}$' then
    raise exception 'Invalid branch';
  end if;
  if p_qr_number is null or p_qr_number not between 1 and 10 then
    raise exception 'QR number must be between 1 and 10';
  end if;

  select session.id
  into active_session_id
  from public.dining_qr_sessions as session
  where session.branch = normalized_branch
    and session.qr_number = p_qr_number
    and session.status = 'active'
  for update;

  if active_session_id is null then
    return null;
  end if;

  update public.dining_qr_sessions
  set status = 'closed',
      ended_at = now(),
      ended_reason = 'table-checkout'
  where id = active_session_id;

  update public.dining_requests
  set status = 'canceled'
  where qr_session_id = active_session_id
    and status not in ('completed', 'canceled');

  return active_session_id;
end;
$$;

alter table public.dining_qr_sessions enable row level security;

revoke all on table public.dining_qr_sessions from anon, authenticated;
grant select on table public.dining_qr_sessions to anon, authenticated;
grant usage, select on sequence public.dining_qr_sessions_id_seq to anon, authenticated;
revoke all on function public.assign_dining_qr_session(text, integer, text) from public;
revoke all on function public.reset_dining_qr_session(text, integer) from public;
grant execute on function public.assign_dining_qr_session(text, integer, text) to anon, authenticated;
grant execute on function public.reset_dining_qr_session(text, integer) to anon, authenticated;

drop policy if exists dining_qr_sessions_public_select on public.dining_qr_sessions;
create policy dining_qr_sessions_public_select
on public.dining_qr_sessions
for select
to anon, authenticated
using (true);

drop policy if exists dining_requests_public_insert on public.dining_requests;
create policy dining_requests_public_insert
on public.dining_requests
for insert
to anon, authenticated
with check (
  status = 'new'
  and source in ('table-qr', 'table-service-call')
  and qr_number between 1 and 10
  and qr_session_id is not null
  and exists (
    select 1
    from public.dining_qr_sessions as session
    where session.id = dining_requests.qr_session_id
      and session.branch = dining_requests.branch
      and session.qr_number = dining_requests.qr_number
      and session.status = 'active'
      and nullif(trim(session.table_code), '') is not null
      and dining_requests.table_code = session.table_code
  )
);

comment on table public.dining_qr_sessions is
  'Durable guest sessions for the ten numbered dining QR codes.';
comment on column public.dining_qr_sessions.table_code is
  'Table assigned for this visit. Null means the QR is not active/assigned.';
comment on column public.dining_requests.qr_session_id is
  'Session that was active when this order or service call was sent.';

commit;
